-- Hotspot test dataset setup
CREATE TABLE hotspot_orders (id INT PRIMARY KEY, user_id INT, amount INT, status STRING);
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (1, 1, 120, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (2, 1, 90, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (3, 1, 75, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (4, 1, 40, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (5, 2, 56, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (6, 2, 30, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (7, 3, 67, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (8, 3, 44, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (9, 4, 150, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (10, 4, 35, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (11, 5, 49, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (12, 5, 38, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (13, 6, 28, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (14, 6, 55, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (15, 7, 89, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (16, 7, 42, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (17, 8, 61, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (18, 8, 47, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (19, 9, 73, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (20, 9, 80, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (21, 10, 24, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (22, 10, 96, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (23, 11, 51, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (24, 11, 77, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (25, 12, 62, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (26, 12, 31, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (27, 13, 59, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (28, 14, 46, 'pending');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (29, 15, 84, 'paid');
INSERT INTO hotspot_orders (id, user_id, amount, status) VALUES (30, 16, 26, 'paid');
SELECT COUNT(*) AS total_rows FROM hotspot_orders;
